# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58cec197cfe4dee79a586fefb6805234a139bf667c2ac4d7a6f3fe1b306f06474da89f96d413285ef5e1293412a0c81e5a924ad3de59059c38fc82249ab2e186

test:
  secret_key_base: e4c8df98f6a2047b6aec28883ec4a659b6de3a629a94e4c1017b5b428670697169115550444c1639f375c6d8bab851fbc6d7eb5aa2e477f991ac0c826856da61

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
